export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const TOGGLE_CRL_THEME = "TOGGLE_CLR_THEME";
