export const FETCH_ENTRIES_REQUEST = "FETCH_ENTRIES_REQUEST";
export const FETCH_ENTRIES_FAILURE = "FETCH_ENTRIES_FAILURE";
export const FETCH_ENTRIES_SUCCESS = "FETCH_ENTRIES_SUCCESS";
export const ADD_NEW_ENTRY = "ADD_NEW_ENTRY";
