export const FETCH_ENTRIES_REQUEST = "FETCH_ENTRIES_REQUEST";
export const FETCH_ENTRIES_FAILURE = "FETCH_ENTRIES_FAILURE";
export const FETCH_ENTRIES_SUCCESS = "FETCH_ENTRIES_SUCCESS";

export const ADD_NEW_ENTRY_REQUEST = "ADD_NEW_ENTRY_REQUEST";
export const ADD_NEW_ENTRY_FAILURE = "ADD_NEW_ENTRY_FAILURE";
export const ADD_NEW_ENTRY_SUCCESS = "ADD_NEW_ENTRY_SUCCESS";

export const DELETE_SINGLE_ENTRY_REQUEST = "DELETE_SINGLE_ENTRY_REQUEST";
export const DELETE_SINGLE_ENTRY_FAILURE = "DELETE_SINGLE_ENTRY_FAILURE";
export const DELETE_SINGLE_ENTRY_SUCCESS = "DELETE_SINGLE_ENTRY_SUCCESS";

export const UPDATE_SINGLE_ENTRY_REQUEST = "UPDATE_SINGLE_ENTRY_REQUEST";
export const UPDATE_SINGLE_ENTRY_FAILURE = "UPDATE_SINGLE_ENTRY_FAILURE";
export const UPDATE_SINGLE_ENTRY_SUCCESS = "UPDATE_SINGLE_ENTRY_SUCCESS";
